# use the official python image from docker hub
FROM python:3.9-slim

#set the working directory 
WORKDIR /app

#copy the requirements file into the container at /app
COPY . /app

#install the dependencies
RUN pip install flask

#make port 5000 available to the world outside this container
EXPOSE 5000

#run the application when the container launches
CMD ["python", "app.py"]
